name: test workflow

on:
  push:
  workflow_dispatch:

jobs:
 run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        java: [ adopt@1.11, adopt@1.16]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - name: Run test
        shell: bash
        run: sbt -v +test
